// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpruqvufarwvycqmymdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwcnVxdnVmYXJ3dnljcW15bWRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNDkzNDksImV4cCI6MjA2MjcyNTM0OX0.s_drf30U14is9qM8Kc96Zytnofl_lm_jERPm5ur1OBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);